name: Rust

on:
  workflow_run:
    workflows: ["Check Codebase"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  runner-job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    services:
      postgis:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5432
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Rust test enabling serde
      run: cargo test --features serde --verbose
    - name: Rust test enabling serde_geojson
      run: cargo test --features serde_geojson --verbose
    - name: Rust test enabling schemars
      run: cargo test --features schemars --verbose