name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Label of the container job
  runner-job:
    # You must use a Linux environment when using service containers or container 
    runs-on: ubuntu-latest
    services:
      postgis:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5432
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Rust test enabling serde
      run: cargo test --features serde --verbose
    - name: Rust test enabling serde_geojson
      run: cargo test --features serde_geojson --verbose
    - name: Rust test enabling schemars
      run: cargo test --features schemars --verbose
    - name: Rust check disabling default features
      run: cargo check --no-default-features --verbose